name: Linter
run-name: ${{ github.actor }} triggered the linter pipe
permissions:
  contents: read
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true

      - name: Set up linter
        uses: golangci/golangci-lint-action@v3

      - name: Run linter
        run: make lint