name: Security
run-name: ${{ github.actor }} triggered the security pipe
permissions:
  contents: read
on: [push]

jobs:
  vulnerability:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
          check-latest: true
      
      - name: Set up govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run vulnerability checks
        run: make vulncheck